# Generated by Django 4.1.6 on 2023-03-25 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_profile',
        ),
        migrations.RemoveField(
            model_name='text',
            name='title',
        ),
        migrations.AddField(
            model_name='text',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
