# Generated by Django 4.1.6 on 2023-03-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_text_date_text_dictionary_text_num_symbols_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='semantic_logistic_regression',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='text',
            name='semantic_native_bayes',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='text',
            name='semantic_sgd',
            field=models.CharField(default='', max_length=20),
        ),
    ]
