# Generated by Django 4.1.6 on 2023-03-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_alter_text_semantic_logistic_regression_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='num_symbols',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='text',
            name='num_symbols_without_space',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='text',
            name='num_words',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
