# Generated by Django 4.1.6 on 2023-03-25 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_alter_text_num_symbols_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='sentiment_logistic_regression_pred',
            new_name='sentiment_logistic_regression',
        ),
    ]
