# Generated by Django 4.1.6 on 2023-03-26 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_rename_sentiment_logistic_regression_pred_text_sentiment_logistic_regression'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='sentiment_logistic_regression',
            new_name='sentiment',
        ),
    ]
