# Generated by Django 4.1.6 on 2023-05-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0008_alter_text_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='semantic_logistic_regression',
        ),
        migrations.RemoveField(
            model_name='text',
            name='semantic_native_bayes',
        ),
        migrations.RemoveField(
            model_name='text',
            name='semantic_sgd',
        ),
        migrations.AddField(
            model_name='text',
            name='semantic',
            field=models.JSONField(default=dict),
        ),
    ]
