# Generated by Django 4.1.6 on 2023-05-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0010_text_text_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='semantic',
            new_name='stopWords',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='text_style',
            new_name='style',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='num_symbols',
            new_name='symbolsCount',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='num_symbols_without_space',
            new_name='symbolsWithoutSpaceCount',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='stop_words',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='num_words',
            new_name='wordsCount',
        ),
    ]
